name: Main

on:
  push:
    branches:
      - 'main'
      # - 'develop'
      # - '*'
      # - '*/*'
      # - '!master'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

env:
  ALI_OSS_SECRET: ${{ secrets.ALI_OSS_SECRET }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用密钥

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.20.0'
      - run: yarn install
      - run: yarn dist
      - run: ./oss.sh mac

  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.20.0'
      - run: yarn install
      - run: yarn dist
      - run: sh ./oss.sh win 
